
CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(1000) NOT NULL,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS project (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS test (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    project_id INT NOT NULL,
    test_data VARCHAR(4000) NOT NULL,
    FOREIGN KEY(project_id) REFERENCES project(id)
);
