
CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(1000) NOT NULL,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS project (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(512) NOT NULL
);
